import type { Metadata } from "next";
import { Inter, Montserrat } from "next/font/google";
import "./globals.css";
import Providers from "./providers";

const inter = Inter({
   subsets: ["latin"],
   variable: "--font-inter",
});

const montserrat = Montserrat({
   subsets: ["latin"],
   variable: "--font-montserrat",
});

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
};

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode;
}>) {
   return (
      <html lang="en" className={`${montserrat.variable} ${inter.variable}`}>
         <body className="antialiased font-primary">
            <Providers>{children}</Providers>
         </body>
      </html>
   );
}
